# Generated by Django 4.1.4 on 2022-12-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='isAvailable',
            new_name='is_vailable',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_pozition',
            new_name='room_position',
        ),
    ]
