# Generated by Django 4.1.4 on 2022-12-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_isavailable_booking_is_vailable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_vailable',
            new_name='is_available',
        ),
    ]
