# Generated by Django 4.1.4 on 2022-12-26 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_is_vailable_booking_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='check_in',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_available',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
