# Generated by Django 4.1.4 on 2022-12-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_booking_room_alter_review_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
