# Generated by Django 4.1.4 on 2022-12-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
    ]
