# Generated by Django 4.1.6 on 2023-02-09 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_phonenumber_phonenumberverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumberverification',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
